src/blog/config/routes.rb
Rails.application.routes.draw do
  get 'testing_site_bookings/index'
  get 'search_booking/index'
  get 'profile/index'
  get 'profile/show', to: 'profile#show'
  get 'profile/modify', to: 'profile#modify'
  get 'profile/cancel', to: 'profile#cancel'
  get 'profile/undo', to: 'profile#undo'
  get 'scan_qr/index'
  get 'create_home_booking/index'
  get 'interview_form/index'
  get 'search_booking/index'
  get 'create_booking/index'
  get 'search_testing_site/index'
  get 'home/index'
  get 'session/index'
  get 'login/index'
  get 'search_booking/search'
  get 'testing_site_bookings/delete', to: 'testing_site_bookings#delete'
  get 'testing_site_bookings/cancel', to: 'testing_site_bookings#cancel'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'login#index'
  post 'login/index', to: 'session#create'
  post 'search_testing_site/index', to: 'search_testing_site#search'
  post 'create_booking/index', to: 'create_booking#create'
  post 'create_home_booking/index', to: 'create_home_booking#create'
  post 'scan_qr/index', to: 'scan_qr#scan_qr'
  post 'search_booking/search', to: 'search_booking#search'
  post 'interview_form/index', to: 'interview_form#submit'
  post 'profile/modify', to: 'profile#submit'
#   post 'profile/undo'
end

src/blog/app/controllers/home_controller.rb
require_relative '../../../handler/user_handler'
require_relative '../../../user/user'
require_relative '../../../user/user_type'

class HomeController < ApplicationController

  def index
  end
  
end

src/blog/app/helpers/home_helper.rb
module HomeHelper
end

src/blog/app/views/home/index.html.erb
<h1>Home</h1>

<%= button_to "Search for Testing Site", search_testing_site_index_path, class: "btn btn-secondary", method: :get %> <br>

<% if @isCustomer or @isReceptionist %>
    <%= button_to "Search Booking", search_booking_search_path, class: "btn btn-secondary", method: :get %> <br>
<% end %>

<% if @isCustomer %> 
    <%= button_to "New Home Booking", create_home_booking_index_path, class: "btn btn-secondary", method: :get %> <br>
    <%= button_to "Profile", profile_index_path, class: "btn btn-secondary", method: :get %> <br>
<% end %> 

<% if @isReceptionist %>
    <%= button_to "New Testing Site Booking", create_booking_index_path, class: "btn btn-secondary", method: :get %> <br>
    <%= button_to "Scan QR", scan_qr_index_path, class: "btn btn-secondary", method: :get %> <br>
    <%= button_to "Testing Site Bookings", testing_site_bookings_index_path, class: "btn btn-secondary", method: :get %> <br>
<% end %>

<% if @isHealthcareWorker %>
    <%= button_to "Interview Form", interview_form_index_path, class: "btn btn-secondary", method: :get %> <br>
<% end %>