src/blog/config/routes.rb
Rails.application.routes.draw do
  get 'testing_site_bookings/index'
  get 'search_booking/index'
  get 'profile/index'
  get 'profile/show', to: 'profile#show'
  get 'profile/modify', to: 'profile#modify'
  get 'profile/cancel', to: 'profile#cancel'
  get 'profile/undo', to: 'profile#undo'
  get 'scan_qr/index'
  get 'create_home_booking/index'
  get 'interview_form/index'
  get 'search_booking/index'
  get 'create_booking/index'
  get 'search_testing_site/index'
  get 'home/index'
  get 'session/index'
  get 'login/index'
  get 'search_booking/search'
  get 'testing_site_bookings/delete', to: 'testing_site_bookings#delete'
  get 'testing_site_bookings/cancel', to: 'testing_site_bookings#cancel'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'login#index'
  post 'login/index', to: 'session#create'
  post 'search_testing_site/index', to: 'search_testing_site#search'
  post 'create_booking/index', to: 'create_booking#create'
  post 'create_home_booking/index', to: 'create_home_booking#create'
  post 'scan_qr/index', to: 'scan_qr#scan_qr'
  post 'search_booking/search', to: 'search_booking#search'
  post 'interview_form/index', to: 'interview_form#submit'
  post 'profile/modify', to: 'profile#submit'
#   post 'profile/undo'
end

src/blog/app/controllers/search_booking_controller.rb
require_relative '../../../handler/booking_handler'

class SearchBookingController < ApplicationController
  
  def index
  end

  def search
    @booking = nil
    if params.key?(:pin_or_id)
      pin_or_id = params[:pin_or_id]
      bookingHandler = BookingHandler.getInstance
      if bookingHandler.isValidPIN(pin_or_id)
        @booking = bookingHandler.getBookingWithPIN(pin_or_id)
      elsif bookingHandler.isValidBookingID(pin_or_id)
        @booking = bookingHandler.getBooking(pin_or_id)
      else
        flash[:notice] = "Invalid PIN or ID!"
        redirect_to action: 'search'
        return
      end
      if @booking == nil
          flash[:notice] = "Booking doesn't exist!"
          redirect_to action: 'search'
      else
        redirect_to profile_show_path(@booking.id)
      end

    else
      render :search
    end
  end

end

src/blog/app/views/search_booking/index.html.erb
<h1>Check Booking Status</h1>

src/blog/app/views/search_booking/search.html.erb
<h1>Check Booking Status</h1>

<%= form_with do |f| %>

    <p>
        Booking PIN or ID:  
        <%= f.search_field :pin_or_id %>
    </p>

    <% flash.each do |type, msg| %>
    <div>
        <h6>
            <%= msg %>
        </h6>
    </div>
    <% end %>


    <p>
        <%= f.submit "Search" %>
    </p>

<% end %>

<% if @booking %>
    <h1>Booking Details</h1>
    <br>
    <%= render(:partial => "layouts/booking", :locals => {:booking => @booking})%>
    <br>

    <h3>Previous Changes</h3>
    <% if not @booking.additionalInfo[:mementos].nil? and not @booking.additionalInfo[:mementos].empty? %>
        <%= render(:partial => "profile/booking_memento_table", :locals => {:booking => @booking, :mementos => @booking.additionalInfo[:mementos]})%>
    <% else %>
        <p>No Previous Changes</p>
    <% end %>


    <div class="container">
        <% if ![BookingStatus::Cancelled, BookingStatus::Lapsed].include? @booking.status %>
            <%= link_to "Modify", profile_modify_path(@booking.id, fromSearch: true), class: "btn btn-secondary", method: :get%>
            <% if (not @booking.additionalInfo[:mementos].nil? and not @booking.additionalInfo[:mementos].empty?) and @booking.additionalInfo[:undoCount] < 3 %>
                <br><%= link_to "Undo", profile_undo_path(@booking.id, fromSearch: true), class: "btn btn-secondary", method: :get%>
            <% end %>
            <br><%= link_to "Cancel", profile_cancel_path(bookingId: @booking.id, fromSearch: true), class: "btn btn-secondary", method: :get%>
        <% end %>
    </div>

<% end %>