src/blog/config/routes.rb
Rails.application.routes.draw do
  get 'testing_site_bookings/index'
  get 'search_booking/index'
  get 'profile/index'
  get 'profile/show', to: 'profile#show'
  get 'profile/modify', to: 'profile#modify'
  get 'profile/cancel', to: 'profile#cancel'
  get 'profile/undo', to: 'profile#undo'
  get 'scan_qr/index'
  get 'create_home_booking/index'
  get 'interview_form/index'
  get 'search_booking/index'
  get 'create_booking/index'
  get 'search_testing_site/index'
  get 'home/index'
  get 'session/index'
  get 'login/index'
  get 'search_booking/search'
  get 'testing_site_bookings/delete', to: 'testing_site_bookings#delete'
  get 'testing_site_bookings/cancel', to: 'testing_site_bookings#cancel'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'login#index'
  post 'login/index', to: 'session#create'
  post 'search_testing_site/index', to: 'search_testing_site#search'
  post 'create_booking/index', to: 'create_booking#create'
  post 'create_home_booking/index', to: 'create_home_booking#create'
  post 'scan_qr/index', to: 'scan_qr#scan_qr'
  post 'search_booking/search', to: 'search_booking#search'
  post 'interview_form/index', to: 'interview_form#submit'
  post 'profile/modify', to: 'profile#submit'
#   post 'profile/undo'
end

src/blog/app/controllers/testing_site_bookings_controller.rb
require_relative '../../../handler/package'
require_relative '../../../registration/package'
require_relative '../../../user/package'

class TestingSiteBookingsController < ApplicationController

  include BookingUpdater

  def index
    user = UserHandler.getInstance.getUserWithJWT(session[:current_user_jwt])
    checkIsAdmin(user)

    testingSiteId = user.testingSiteId
    testingSite = TestingSiteHandler.getInstance.getTestingSite(testingSiteId)
    @bookings = testingSite.bookings.map{ |booking| BookingHandler.getInstance.getBooking(booking.id)}

  end

  def delete
    bookingId = params[:bookingId]
    booking = BookingHandler.getInstance.getBooking(bookingId)
    response = BookingHandler.getInstance.deleteBooking(bookingId)
    flash[:notice] = response[:details]

    if response[:success]
      bookingUpdated(booking.id, "Booking Deleted", booking.getTestingSiteId)
    end

    redirect_back fallback_location: testing_site_bookings_index_path
  end

  def cancel
    bookingId = params[:bookingId]
    booking = BookingHandler.getInstance.getBooking(bookingId)
    response = BookingHandler.getInstance.cancelBooking(bookingId)
    flash[:notice] = response[:details]

    if response[:success]
      bookingUpdated(booking.id, "Booking Cancelled", booking.getTestingSiteId)
    end

    redirect_back fallback_location: testing_site_bookings_index_path
  end

  def checkIsAdmin(user)
    if not user.userType == UserType::Receptionist
      flash[:notice] = "You're not an admin."
      redirect_to home_index_url
    end 
  end

end

src/blog/app/helpers/testing_site_bookings_helper.rb
module TestingSiteBookingsHelper
end

src/blog/app/views/testing_site_bookings/index.html.erb
<% flash.each do |type, msg| %>
  <div style="text-align:center">
    <h6>
        <%= msg %>
    </h6>
  </div>
<% end %>

<h1>All Bookings</h1>

<div id="testing_site_bookings_table" , class="table-responsive">
 <table class="table table-striped table-bordered table-hover">
        <tr class="table-dark">
            <th>Booking Id </th>              
            <th>Testing Site </th>
            <th>Appointment Date</th>
            <th>Last Modified</th>
            <th>User</th>
            <th>Status</th>
            <th></th>
        </tr>
    
        <% @bookings.each_with_index do |booking, i| %>
            <tr>
                <td><%=booking.id %></td>
                <td>NAME: <%=booking.testingSiteData[:name] %><br> ID: <%=booking.testingSiteData[:id] %></td>
                <td><%=booking.startTime %></td>
                <td><%=booking.updatedAt %></td>
                <td><%=booking.customer[:userName] %></td>
                <td><%=booking.status %></td>
                <td><%= link_to "Show", profile_show_path(booking.id)%><br>
                    <%= link_to "Delete", testing_site_bookings_delete_path(bookingId: booking.id) %> <br>
                    <% if ![BookingStatus::Cancelled, BookingStatus::Lapsed].include? booking.status %>
                        <%= link_to "Cancel", testing_site_bookings_cancel_path(bookingId: booking.id) %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table> 
 </div>